#!/usr/bin/env python3
"""Build the arm4090 teleop URDF (OpenArm + RH56F1 + head) from the hdgp asset.

    .venv/bin/python scripts/build_openarm_rh56f1_urdf.py \
        [--src ~/rl_ws/hdgp/assets/robot/openarm_rh56f1_bi_rl/openarm_rh56f1_bi_rl.urdf]

Changes from the hdgp asset, nothing else:
- arm joints r_aj_i / l_aj_i -> openarm_<side>_joint<i> (the OpenArm driver and
  the robot YAML use these names; geometry, limits and axes are untouched);
- every hand and head joint becomes fixed at the sim2real contract pose
  (RH56F1 open: thumb_1 = 1.57 rad, the rest 0; head pan/tilt 0). Teleop IK
  drives the arms only; the hand pose is baked into the fixed origins;
- adds openarm_<side>_hand_tcp, a fixed child of <r|l>_hl_palm_sensor with an
  identity offset (the palm contact frame used by sim2real).
Meshes stay where the hdgp asset points (file:///home/user/rl_ws/urdf/...);
IK loads the URDF without meshes, only visualisation needs them.
The output header records the source path and sha256; --check verifies that
the committed URDF matches a fresh build.
"""

from __future__ import annotations

import argparse
import hashlib
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

import numpy as np
from scipy.spatial.transform import Rotation

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SRC = Path.home() / "rl_ws/hdgp/assets/robot/openarm_rh56f1_bi_rl/openarm_rh56f1_bi_rl.urdf"
OUT = ROOT / "assets" / "openarm_rh56f1" / "openarm_rh56f1.urdf"
SIDES = {"r": "right", "l": "left"}
# sim2real contract hand_home (RH56F1 open) and head at zero; mimic joints follow.
BAKED = {"hj_thumb_1": 1.57}
MIMIC_GAIN = {"hj_thumb_3": ("hj_thumb_2", 1.1425), "hj_thumb_4": ("hj_thumb_3", 0.7508)}


def _floats(text: str | None, n: int = 3) -> np.ndarray:
    return np.array([float(v) for v in (text or " ".join(["0"] * n)).split()], dtype=np.float64)


def _fmt(values: np.ndarray) -> str:
    return " ".join(f"{v:.10g}" for v in values)


def joint_angle(name: str, angles: dict[str, float]) -> float:
    """Baked angle for a hand/head joint (side prefix stripped), mimic resolved."""
    if name in BAKED:
        return BAKED[name]
    if name in MIMIC_GAIN:
        source, gain = MIMIC_GAIN[name]
        return gain * joint_angle(source, angles)
    return angles.get(name, 0.0)


def build(src: Path) -> str:
    raw = src.read_bytes()
    robot = ET.fromstring(raw)
    robot.set("name", "openarm_rh56f1")
    for joint in robot.findall("joint"):
        name = joint.get("name", "")
        side_tag, _, rest = name.partition("_")
        if rest.startswith("aj_") and rest[3:].isdigit() and side_tag in SIDES:
            joint.set("name", f"openarm_{SIDES[side_tag]}_joint{rest[3:]}")
            continue
        if joint.get("type") not in ("revolute", "continuous", "prismatic"):
            continue
        if not (rest.startswith("hj_") or name.startswith("head_j_")):
            raise SystemExit(f"unexpected movable joint {name!r}")
        key = rest if rest.startswith("hj_") else name
        angle = joint_angle(key, {})
        origin = joint.find("origin")
        if origin is None:
            origin = ET.SubElement(joint, "origin", xyz="0 0 0", rpy="0 0 0")
        axis_el = joint.find("axis")
        axis = _floats(axis_el.get("xyz") if axis_el is not None else "1 0 0")
        if joint.get("type") == "prismatic":
            raise SystemExit(f"prismatic {name} not expected")
        r_origin = Rotation.from_euler("xyz", _floats(origin.get("rpy")))
        r_joint = Rotation.from_rotvec(axis / np.linalg.norm(axis) * angle)
        origin.set("rpy", _fmt((r_origin * r_joint).as_euler("xyz")))
        joint.set("type", "fixed")
        for tag in ("axis", "limit", "mimic", "dynamics", "safety_controller"):
            for child in joint.findall(tag):
                joint.remove(child)
    for tag, side in SIDES.items():
        link = ET.SubElement(robot, "link", name=f"openarm_{side}_hand_tcp")
        link.text = None
        joint = ET.SubElement(robot, "joint", name=f"openarm_{side}_hand_tcp_joint", type="fixed")
        ET.SubElement(joint, "parent", link=f"{tag}_hl_palm_sensor")
        ET.SubElement(joint, "child", link=f"openarm_{side}_hand_tcp")
        ET.SubElement(joint, "origin", xyz="0 0 0", rpy="0 0 0")
    ET.indent(robot)
    body = ET.tostring(robot, encoding="unicode")
    header = (
        '<?xml version="1.0"?>\n'
        f"<!-- Generated by scripts/build_openarm_rh56f1_urdf.py from {src} "
        f"(sha256 {hashlib.sha256(raw).hexdigest()}). Do not edit by hand. -->\n"
    )
    return header + body + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--src", type=Path, default=DEFAULT_SRC)
    ap.add_argument("--check", action="store_true", help="fail if the committed URDF is stale")
    args = ap.parse_args()
    text = build(args.src)
    if args.check:
        if not OUT.exists() or OUT.read_text() != text:
            print(f"{OUT} is stale; rebuild it")
            return 1
        print("up to date")
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text)
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
